# Generated by Django 4.2 on 2023-07-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('phone_number', models.PositiveIntegerField()),
                ('address_city', models.CharField(max_length=30)),
                ('address_country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=15, null=True)),
                ('country_code', models.IntegerField()),
                ('phone_number', models.PositiveIntegerField()),
                ('address_city', models.CharField(max_length=30)),
                ('address_region', models.CharField(max_length=30)),
                ('address_country', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField()),
            ],
        ),
    ]
