# Generated by Django 4.2.3 on 2023-07-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_league_topmatch_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
