# Generated by Django 4.2.3 on 2023-07-23 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_league_league_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('odd_home', models.FloatField(null=True)),
                ('odd_draw', models.FloatField(null=True)),
                ('odd_away', models.FloatField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('odd_over', models.FloatField(null=True)),
                ('odd_under', models.FloatField(null=True)),
                ('odd_both_score_yes', models.FloatField(null=True)),
                ('odd_both_score_no', models.FloatField(null=True)),
                ('comp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.league')),
            ],
        ),
        migrations.CreateModel(
            name='NextToGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('odd_home', models.FloatField(null=True)),
                ('odd_draw', models.FloatField(null=True)),
                ('odd_away', models.FloatField(null=True)),
                ('time', models.TimeField(null=True)),
                ('comp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.league')),
            ],
        ),
    ]
