# Generated by Django 4.2.3 on 2023-07-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_remove_user_address_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
