# Generated by Django 4.2 on 2023-07-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('country_code', models.IntegerField()),
                ('phone_number', models.PositiveIntegerField()),
                ('address_city', models.CharField(max_length=30)),
                ('address_region', models.CharField(max_length=30)),
                ('address_country', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('odd_home', models.FloatField(null=True)),
                ('odd_draw', models.FloatField(null=True)),
                ('odd_away', models.FloatField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('odd_over', models.FloatField(null=True)),
                ('odd_under', models.FloatField(null=True)),
                ('odd_both_score_yes', models.FloatField(null=True)),
                ('odd_both_score_no', models.FloatField(null=True)),
                ('comp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bet.league')),
            ],
        ),
        migrations.CreateModel(
            name='TopMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name1', models.CharField(max_length=50)),
                ('country1_flag', models.ImageField(upload_to='')),
                ('country_name2', models.CharField(max_length=50)),
                ('country2_flag', models.ImageField(upload_to='')),
                ('date', models.DateTimeField()),
                ('odd_home', models.FloatField(null=True)),
                ('odd_draw', models.FloatField(null=True)),
                ('odd_away', models.FloatField(null=True)),
                ('comp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bet.league')),
            ],
        ),
        migrations.CreateModel(
            name='NextToGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('odd_home', models.FloatField(null=True)),
                ('odd_draw', models.FloatField(null=True)),
                ('odd_away', models.FloatField(null=True)),
                ('time', models.TimeField(null=True)),
                ('comp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bet.league')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bet.league')),
            ],
        ),
    ]
