# Generated by Django 4.2.3 on 2023-07-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nexttogo',
            name='comp_name',
        ),
        migrations.RemoveField(
            model_name='topmatch',
            name='comp_name',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='comp_name',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='NextToGo',
        ),
        migrations.DeleteModel(
            name='TopMatch',
        ),
        migrations.DeleteModel(
            name='Trending',
        ),
    ]
