# Generated by Django 4.2 on 2023-07-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bet', '0002_remove_nexttogo_comp_name_remove_topmatch_comp_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
